# Generated by Django 4.2.7 on 2026-04-16 16:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('minimo_requerido', models.PositiveSmallIntegerField(default=0, help_text='Mínimo % requerido para el área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.TextField(blank=True)),
                ('video_ayuda', models.URLField(blank=True)),
                ('nivel_critico', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('tiempo_estimado', models.PositiveIntegerField(blank=True, help_text='Minutos estimados', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='core.area')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('auditor', 'Auditor'), ('operador', 'Operador')], default='operador', max_length=20)),
                ('minimo_porcentaje', models.PositiveSmallIntegerField(default=0, help_text='Porcentaje mínimo requerido')),
                ('puede_gestionar_staff', models.BooleanField(default=False)),
                ('puede_gestionar_areas', models.BooleanField(default=False)),
                ('puede_gestionar_procesos', models.BooleanField(default=False)),
                ('puede_gestionar_pasos', models.BooleanField(default=False)),
                ('puede_supervisar', models.BooleanField(default=False)),
                ('area_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='core.area')),
                ('equipo_a_cargo', models.ManyToManyField(blank=True, related_name='supervisores', to='core.staffprofile')),
                ('procesos_asignados', models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='core.proceso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('regla', models.CharField(help_text='Ej: "lunes,miercoles" para semanal, "15" para mensual, o "*" para diaria', max_length=100)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='core.proceso')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'Planificación',
                'verbose_name_plural': 'Planificaciones',
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('condicional', 'Condicional')], default='normal', max_length=20)),
                ('puntos', models.PositiveSmallIntegerField(default=1)),
                ('orden', models.PositiveSmallIntegerField()),
                ('ayuda_html', ckeditor.fields.RichTextField(blank=True, help_text='Contenido HTML de ayuda', null=True)),
                ('pregunta_condicion', models.CharField(blank=True, help_text='Pregunta si el paso es condicional', max_length=255, null=True)),
                ('nivel_critico', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('evidencia_tipo', models.CharField(choices=[('ninguna', 'Ninguna'), ('fotografica', 'Solo fotográfica'), ('descriptiva', 'Solo descriptiva'), ('ambas', 'Fotográfica y descriptiva')], default='ninguna', help_text='Tipo de evidencia requerida', max_length=20)),
                ('paso_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condicion_no', to='core.paso')),
                ('paso_si', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condicion_si', to='core.paso')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='core.proceso')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('proceso', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='EjecucionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('supervisado', 'Supervisado'), ('auditado', 'Auditado')], default='en_progreso', max_length=20)),
                ('puntos_obtenidos', models.PositiveSmallIntegerField(default=0)),
                ('puntos_totales', models.PositiveSmallIntegerField(default=0)),
                ('comentario_general', models.TextField(blank=True, help_text='Comentario de supervisión/auditoría')),
                ('estado_supervision', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('resultado_supervision', models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='core.proceso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='core.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('saltado', 'Saltado')], default='pendiente', max_length=20)),
                ('respuesta_condicion', models.BooleanField(blank=True, null=True)),
                ('evidencia_fotografica', models.ImageField(blank=True, null=True, upload_to='evidencias/fotos/')),
                ('evidencia_descriptiva', models.TextField(blank=True)),
                ('tiempo_inicio', models.DateTimeField(auto_now_add=True)),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('puntaje_original', models.PositiveSmallIntegerField(default=0)),
                ('puntaje_ajustado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentario_supervision', models.TextField(blank=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_ejecutados', to='core.ejecucionproceso')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paso')),
            ],
            options={
                'ordering': ['paso__orden'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_a_cargo', to='core.staffprofile'),
        ),
    ]
